### ISSUE TITLE
Header

### ISSUE THREAD

**Issue by xdima92x** [livecomposer/live-composer-page-builder#181]
https://cl.ly/h5B0 - here, you'll see that I have the Header menu style set to Fixed. This should allow for the sticky header. However, with it set to Fixed, the theme is also putting the content of that module area BEHIND the menu, just like it does with the Absolute setting.

**Comment by livecomposer** [comment]
Fixed in new update.

Issue [#181](https://github.com/livecomposer/live-composer-page-builder/issues/181): Fixed headers cover working area while editing page. From now Fixed / Absolute headers will looks like a regular header in editing more. If you want to see it fixed as on production, please click on "Hide Editor" button.
